const restaurantList = [
  {
    data: {
      id: "260595",
      name: "Wow! Momo",
      cloudinaryImageId: "5a148e63e9c54942e37627da1aa156be",
      delieveryTime: 56,
      address: "Camp",
      costForTwo: "₹300 for two",
      cuisines: [
        "Tibetan",
        "Healthy Food",
        "Asian",
        "Chinese",
        "Snacks",
        "Continental",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.2,
    },
  },
  {
    data: {
      id: "24439",
      name: "Domino's Pizza",
      cloudinaryImageId: "xqepd6rivebgewjgi3sj",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      delieveryTime: 25,
      address: "Vishrantwadi",
      avgRating: 4.3,
    },
  },
  {
    data: {
      id: "23675",
      name: "McDonald's",
      cloudinaryImageId: "03501c33ecb3a3105124441e541e6fe4",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      delieveryTime: 31,
      address: "Kalyani Nagar",
      avgRating: 4.5,
    },
  },
  {
    data: {
      id: "11607",
      name: "Mad Momos",
      cloudinaryImageId: "pw5iq9ufesy1m4yy68pw",
      cuisines: [
        "Chinese",
        "Tibetan",
        "Nepalese",
        "Pizzas",
        "Snacks",
        "Beverages",
      ],
      delieveryTime: 29,
      address: "Tingare Nagar",
      avgRating: 4.1,
    },
  },
  {
    data: {
      id: "71867",
      name: "Faasos - Wraps, Rolls & Shawarma",
      cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
      cuisines: [
        "Kebabs",
        "Fast Food",
        "Snacks",
        "American",
        "Healthy Food",
        "Desserts",
        "Beverages",
      ],
      delieveryTime: 34,
      address: "Viman Nagar",
      avgRating: 4.3,
    },
  },
  {
    data: {
      id: "71872",
      name: "LunchBox - Meals and Thalis",
      cloudinaryImageId: "fb3enuojckiszvafryo3",
      cuisines: [
        "Biryani",
        "North Indian",
        "Punjabi",
        "Healthy Food",
        "Desserts",
        "Beverages",
      ],
      delieveryTime: 35,
      address: "Viman Nagar",
      avgRating: 4.3,
      costForTwo: "₹200 for two",
    },
  },
  {
    data: {
      id: "188935",
      name: "Theobroma",
      cloudinaryImageId: "b033728dcb0101ceb19bff0e1e1f6474",
      cuisines: ["Bakery", "Desserts"],
      delieveryTime: 30,
      address: "Viman Nagar",
      costForTwo: "₹400 for two",
      avgRating: 4.5,
    },
  },
  {
    data: {
      id: "156139",
      name: "The Good Bowl",
      cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
      cuisines: [
        "Biryani",
        "North Indian",
        "Pastas",
        "Punjabi",
        "Desserts",
        "Beverages",
      ],
      delieveryTime: "35-45",
      address: "Sakore Nagar",
      costForTwo: "₹400 for two",
      avgRating: 4.3,
    },
  },
  {
    data: {
      id: "8777",
      name: "Subway",
      cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
      address: "Viman Nagar",
      costForTwo: "₹350 for two",
      cuisines: [
        "Healthy Food",
        "Salads",
        "Snacks",
        "Desserts",
        "Beverages",
        "North Indian",
        "Indian",
        "Italian",
      ],
      avgRating: 4,
      delieveryTime: "40-50",
    },
  },
  {
    data: {
      id: "438229",
      name: "Papacream",
      cloudinaryImageId: "78d791f3f4494b28a4ed376fabbb6d9d",
      address: "Pimple Saudagar",
      costForTwo: "₹350 for two",
      cuisines: ["Ice Cream", "Desserts", "Cakes and Pastries", "Healthy Food"],
      avgRating: 4.3,
      delieveryTime: 28 + " minutes ",
    },
  },
  {
    data: {
      id: "284806",
      name: "Starbucks Coffee",
      cloudinaryImageId: "182191ab163770437b62861a6f987709",
      address: "Kalyani Nagar",
      costForTwo: "₹400 for two",
      cuisines: [
        "Beverages",
        "Cafe",
        "Snacks",
        "Desserts",
        "Bakery",
        "Ice Cream",
      ],
      avgRating: 4.6,
      delieveryTime: 32 + " minutes ",
    },
  },
  {
    data: {
      id: "522739",
      name: "EatFit",
      cloudinaryImageId: "543307dc74eeb9dc5e0a58c81fe54996",
      address: "Hinjewadi",
      costForTwo: "₹270 for two",
      cuisines: [
        "Chinese",
        "Healthy Food",
        "Tandoor",
        "Pizzas",
        "North Indian",
        "Thalis",
        "Biryani",
      ],
      avgRating: 4.3,
      delieveryTime: 36 + " minutes ",
    },
  },
  // {
  //   data: {
  //     name: "Fisherman's Wharf",
  //     cuisines: ["Seafood", "Goan"],
  //     delieveryTime: "45-55",
  //     address: "Kothrud",
  //     avgRating: 4.7,
  //     cloudinaryImageId: "",
  //   },
  // },
  // {
  //   data: {
  //     name: "Quick Bites",
  //     cuisines: ["Fast Food", "Snacks"],
  //     delieveryTime: "15-25",
  //     address: "FC Road",
  //     avgRating: 3.0,
  //     cloudinaryImageId: "",
  //   },
  // },
  // {
  //   data: {
  //     name: "Arabian Nights",
  //     cuisines: ["Middle Eastern", "Kebabs"],
  //     delieveryTime: "40-50",
  //     address: "Hadapsar",
  //     avgRating: 4.3,
  //     cloudinaryImageId: "",
  //   },
  // },
  // {
  //   data: {
  //     name: "Frozen Yogurt Land",
  //     cuisines: ["Desserts", "Yogurt"],
  //     delieveryTime: "10-20",
  //     address: "NIBM Road",
  //     avgRating: 4.6,
  //     cloudinaryImageId: "",
  //   },
  // },
];

export default restaurantList;
